# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lname',
            field=models.CharField(default=b'SOMETHING', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=b'SOMETHING', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(default=b'SOMETHING', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='mname',
            field=models.CharField(default=b'SOMETHING', max_length=20),
        ),
    ]
