# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_auto_20160524_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='STS_Bracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidy', models.IntegerField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='school_info',
            name='sts_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sts_bracket',
            name='sts_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.School_Info'),
        ),
    ]
