# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_auto_20160524_2022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School_Info',
            new_name='SchoolInfo',
        ),
        migrations.RenameModel(
            old_name='STS_Bracket',
            new_name='STSBracket',
        ),
    ]
