# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_auto_20160524_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
        migrations.RenameField(
            model_name='schoolinfo',
            old_name='course_id',
            new_name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='account',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.SchoolInfo'),
        ),
    ]
