# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_auto_20160527_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stsbracket',
            name='sts_code',
        ),
        migrations.DeleteModel(
            name='STSBracket',
        ),
    ]
