# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_auto_20160527_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='maritalstatus',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
