# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0014_webaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webaccount',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='WebAccount',
        ),
    ]
