# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_auto_20160524_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sts_bracket',
            name='subsidy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
